version: '2'
services:
  wilcuma:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    expose:
      - '4009'
  db:
    build:
      context: ./db-server
    env_file:
      - ./db-server/.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: always
volumes:
  db-data:
    external:
      name: wilcuma-db-data